# Generated by Django 4.1.7 on 2023-04-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choise_is_true_alter_choise_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
    ]
