# Generated by Django 4.1.7 on 2023-04-05 03:57

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choise_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.fields.BooleanField, to='polls.question'),
        ),
    ]
